/**
 * Snapshot the NABC AgriAPI figures the app needs, at authoring time.
 *
 *   node scripts/fetch-nabc.mjs
 *
 * Writes src/data/nabc_maize.json, which is committed.
 *
 * WHY A SNAPSHOT AND NOT A RUNTIME FETCH. The app originally called
 * https://agriapi.nabc.go.th on each plan run. That works from a laptop in Thailand — 0.5s,
 * HTTP 200, 380 KB — and returns nothing at all from a Vercel function, so the whole maize
 * comparison silently vanished in production and only a local-versus-production diff caught
 * it. Most likely the API does not serve requests from Vercel's egress, but the cause matters
 * less than the fact: the runtime path cannot be relied on.
 *
 * A snapshot is also simply the right shape for this data. Province yield is published once a
 * year, so fetching it per request was always wasteful. The monthly price does go stale, which
 * is why fetchedAt and the data's own period are both recorded and both shown to the farmer —
 * a visibly dated number is honest in a way a silently missing section is not.
 *
 * Re-run this when OAE publishes: yield around October for field crops, price monthly.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, '..', 'src', 'data', 'nabc_maize.json');

const BASE = 'https://agriapi.nabc.go.th';
const NAN = 'TH55';
const MAIZE = 'ข้าวโพดเลี้ยงสัตว์';

async function getJson(path) {
  const res = await fetch(`${BASE}${path}`, { signal: AbortSignal.timeout(30000) });
  if (!res.ok) throw new Error(`${path} -> HTTP ${res.status}`);
  return res.json();
}

const rowsOf = (p) => (p && typeof p === 'object' && Array.isArray(p.data) ? p.data : []);

const [prod, price] = await Promise.all([
  getJson(`/api/production/by-commod?commod=${encodeURIComponent(MAIZE)}&api_type=3&limit=1000`),
  getJson(`/api/monthly-prices/commod?commod=${encodeURIComponent(MAIZE)}&limit=24`),
]);

// "รวมรุ่น" is the combined figure across planting rounds; per-round rows would undercount a
// farmer's annual harvest.
const nan = rowsOf(prod)
  .filter((r) => r?.province_code === NAN
    && typeof r.subcommod === 'string' && r.subcommod.includes('รวมรุ่น')
    && typeof r.yield_plant === 'number' && r.yield_plant > 0)
  .sort((a, b) => String(b.year_crop).localeCompare(String(a.year_crop)));

if (!nan.length) throw new Error('no Nan maize rows with a yield — API shape may have changed');

const priceRow = rowsOf(price)
  .find((r) => r?.value != null && Number.isFinite(Number(r.value)) && Number(r.value) > 0);
if (!priceRow) throw new Error('no usable maize price row');

const latest = nan[0];
const earliest = nan[nan.length - 1];

const snapshot = {
  _comment: 'Generated by scripts/fetch-nabc.mjs — do not edit by hand. Re-run to refresh.',
  fetchedAt: new Date().toISOString().slice(0, 10),
  source: 'NABC AgriAPI (ศูนย์ข้อมูลเกษตรแห่งชาติ / สศก.)',
  yieldKgPerRai: latest.yield_plant,
  yieldYear: latest.year_crop,
  yieldScope: 'จังหวัดน่าน (TH55)',
  areaRai: latest.area_plant ?? 0,
  areaEarliestRai: earliest !== latest ? (earliest.area_plant ?? null) : null,
  areaEarliestYear: earliest !== latest ? earliest.year_crop : null,
  pricePerKg: Number(priceRow.value),
  priceYear: priceRow.year_th,
  priceMonth: priceRow.month,
  // Every price record the API returns carries province_code TH00; no sub-national price
  // series is published, and a village buying point pays less than a national average.
  priceScope: 'ระดับประเทศ (ไม่มีราคารายจังหวัด)',
};

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, `${JSON.stringify(snapshot, null, 2)}\n`);
console.log(`wrote ${OUT}`);
console.log(`  yield ${snapshot.yieldKgPerRai} kg/rai (${snapshot.yieldYear}, Nan)`);
console.log(`  price ${snapshot.pricePerKg} THB/kg (${snapshot.priceMonth}/${snapshot.priceYear}, national)`);
console.log(`  area  ${snapshot.areaEarliestRai?.toLocaleString?.() ?? '?'} -> ${snapshot.areaRai.toLocaleString()} rai`);
