import { describe, it, expect } from 'vitest';
import { fetchMaizeBaseline, maizeTenYear, MAIZE_COST_PER_RAI_OAE } from './nabc';
import snapshot from '../data/nabc_maize.json';

/**
 * The maize baseline is the number every plan is judged against, and the only genuinely
 * Nan-specific figure in the tool. It had no test.
 *
 * It is also the number most likely to rot quietly: the snapshot is regenerated by hand with
 * scripts/fetch-nabc.mjs, so a run against a changed API shape can write a plausible-looking
 * file full of wrong values. These check the snapshot itself, not the fetch.
 */
describe('maize baseline snapshot', () => {
  it('is a Nan province yield, not the national average', async () => {
    const baseline = await fetchMaizeBaseline();
    expect(baseline).not.toBeNull();
    expect(snapshot.yieldScope).toContain('น่าน');
    // Nan runs ~693 kg/rai against a national ~790. If a refresh ever lands on the national
    // figure the whole comparison quietly overstates a Nan harvest by about 14%, and nothing
    // on screen would look wrong.
    expect(baseline!.yieldKgPerRai).toBeGreaterThan(400);
    expect(baseline!.yieldKgPerRai).toBeLessThan(760);
  });

  it('labels the price as national, because no sub-national series exists', () => {
    // Every price record the API returns carries province_code TH00. Presenting it as a Nan
    // price would flatter the baseline a farmer is being asked to walk away from.
    expect(snapshot.priceScope).toContain('ระดับประเทศ');
  });

  it('computes net from the three numbers it shows the farmer', async () => {
    const baseline = await fetchMaizeBaseline();
    const expected = Math.round(baseline!.yieldKgPerRai * baseline!.pricePerKg - MAIZE_COST_PER_RAI_OAE);
    expect(baseline!.netPerRaiYear).toBe(expected);
    // A farmer should be able to reproduce it on a phone calculator from what is on screen.
    expect(baseline!.costPerRai).toBe(MAIZE_COST_PER_RAI_OAE);
  });

  it('leaves maize profitable, or the comparison is meaningless', async () => {
    const baseline = await fetchMaizeBaseline();
    // Not a given — at 4,351.8 THB/rai/yr of cost, a price drop below about 6.3 THB/kg makes
    // maize a loss and the "X times better" framing stops being the right one to show.
    expect(baseline!.netPerRaiYear).toBeGreaterThan(0);
  });

  it('carries the date it was taken', async () => {
    const baseline = await fetchMaizeBaseline();
    // The yield is annual and ages slowly; the price is a monthly series frozen at snapshot
    // time. A visibly dated number is honest, a silently stale one is not.
    expect(baseline!.fetchedAt).toMatch(/^\d{4}-\d{2}-\d{2}$/);
  });

  it('records the planted-area trend it claims to show', () => {
    // "พื้นที่ปลูกข้าวโพดใน จ.น่าน ลดลง N%" is rendered from these two, so a snapshot missing
    // the earlier year silently drops the most persuasive line on the card.
    expect(snapshot.areaEarliestRai).toBeGreaterThan(snapshot.areaRai);
    expect(snapshot.areaEarliestYear).toBeTruthy();
  });
});

describe('maizeTenYear', () => {
  it('scales the annual net over ten years and the whole plot', async () => {
    const baseline = await fetchMaizeBaseline();
    expect(maizeTenYear(baseline!, 10)).toBe(Math.round(baseline!.netPerRaiYear * 100));
  });

  it('treats a nonsense plot size as zero rather than negative income', async () => {
    const baseline = await fetchMaizeBaseline();
    expect(maizeTenYear(baseline!, -5)).toBe(0);
    expect(maizeTenYear(baseline!, 0)).toBe(0);
  });
});
